mod annotations;
mod keywords;
mod builtin_types;

use tower_lsp::lsp_types::*;

use poniescript_core::{
    db::*, expr::*, lexer::Token, source::SourceLocation
};

use crate::{document::{DocumentStore, inverse_convert_position}, documentation, semantic_locate::cursor_on};

enum CompletionContext {
    MembersOfType(TypId),
    Unknown,
}

struct CompletionLocator {
    context: CompletionContext,
}

// TODO: Deduplicate this
macro_rules! into {
    ($value:expr, $variant:ident) => {
        {
            let Expr::$variant(v) = $value else { unreachable!() };
            v
        }
    };
}

macro_rules! into_stmt {
    ($value:expr, $variant:ident) => {
        {
            let Stmt::$variant(v) = $value else { unreachable!() };
            v
        }
    };
}

impl poniescript_core::expr::LocateAst for CompletionLocator {


    fn locate_get(&mut self, ast: &Ast, db: &Db, _loc: &SourceLocation, it: &Get) {
        eprintln!("completion: checking get");
        for (idx, var) in it.chain.iter().enumerate() {
            if cursor_on(_loc, &var.location) {
                eprintln!("trying to lookup completions for: {}", db.get(var.lexeme));
                // Okay, try to auto complete based on this var's parents.
                let typ = if idx >= 1 {
                    it.vars.get(idx - 1)
                        .map(|c| db.get_var_type(*c))
                }
                else {
                    Some(it.lhs.typ(ast, db))
                };

                if let Some(typ) = typ {
                    self.context = CompletionContext::MembersOfType(typ)
                }
            }
        }
    }

    fn locate_set(&mut self, ast: &Ast, db: &Db, _loc: &SourceLocation, it: &Set) {
        eprintln!("completion: checking set");
        for (idx, var) in it.chain.iter().enumerate() {
            if cursor_on(_loc, &var.location) {
                eprintln!("trying to lookup completions for: {}", db.get(var.lexeme));
                // Okay, try to auto complete based on this var's parents.
                let typ = if idx >= 1 {
                    it.vars.get(idx - 1)
                        .map(|c| db.get_var_type(*c))
                }
                else {
                    Some(it.lhs.typ(ast, db))
                };

                if let Some(typ) = typ {
                    self.context = CompletionContext::MembersOfType(typ)
                }
            }
        }
    }

    // For now, manually implement the visiting of class declares, because the
    // autogenerated logic doesn't work correctly.
    fn visit_classdeclare(&mut self, ast: &Ast, db: &Db, loc: &SourceLocation, stmt: &ClassDeclare) -> bool {
		let own_loc = &stmt.location;
		eprintln!("visit ClassDeclare: {} ? {} ? {}", own_loc.offset, loc.offset, own_loc.offset + own_loc.length);
		if loc.offset < own_loc.offset { return false; }
		if loc.offset >= own_loc.offset + own_loc.length { return false; }
        for declare in &stmt.vars {
            if self.visit_declare(ast, db, loc, declare) { return true; }
        }
        for fundeclare in &stmt.funs {
            if self.visit_fundeclare(ast, db, loc, fundeclare) { return true; }
        }
		eprintln!("-> found @ ClassDeclare");
		self.locate_classdeclare(ast, db, loc, &stmt);
		return true;
	}

    // For now, also manually implement new, to visit the inner initializers.
    fn visit_new(&mut self, ast: &Ast, db: &Db, loc: &SourceLocation, expr: &New) -> bool {
		let own_loc = &expr.location;
		eprintln!("visit New: {} ? {} ? {}", own_loc.offset, loc.offset, own_loc.offset + own_loc.length);
		if loc.offset < own_loc.offset { return false; }
		if loc.offset >= own_loc.offset + own_loc.length { return false; }
        for init in &expr.initializers {
            if cursor_on(loc, &init.ident.location) {
                return true;
            }
            if self.visit_expr(ast, db, loc, init.value) {
                return true;
            }
        }
		eprintln!("-> found @ New");
		self.locate_new(ast, db, loc, &expr);
		return true;
	}
}

fn var_completions(db: &Db, context: &CompletionContext, completions: &mut Vec<CompletionItem>) {
    let filter: Box<dyn Fn(VarId) -> bool> = match context {
        CompletionContext::MembersOfType(typ) => Box::new(|var_id: VarId| {
            let var = db.get(var_id);
            let lookup = db.lookup_property(*typ, var.name);
            
            // Check whether that type has this item as a lookup.
            lookup == Some(var_id)
        }),
        _ => Box::new(|_var: VarId| { true })
    };

    for var in db.iter_var() {
        if !filter(var) { continue; }

        let var = db.get(var);

        let kind = match var.class {
            Some(_) => CompletionItemKind::FIELD,
            None    => CompletionItemKind::VARIABLE,
        };

        completions.push(CompletionItem {
            label: db.get(var.name).to_string(),
            label_details: Some(CompletionItemLabelDetails {
                detail: Some(format!(": {}", db.repr_type(var.typ))),
                description: None
            }),
            kind: Some(kind),
            documentation: documentation::inefficient_doc_lsp(db, &var.doc_comment),
            ..Default::default()
        })
    }
}

fn fun_completions(db: &Db, context: &CompletionContext, completions: &mut Vec<CompletionItem>) {
    let filter: Box<dyn Fn(FunId) -> bool> = match context {
        CompletionContext::MembersOfType(typ) => Box::new(|fun_id: FunId| {
            let fun = db.get(fun_id);
            // Can't lookup/autocomplete anonymous functions.
            let Some(name) = fun.name else { return false; };
            let lookup = db.lookup_member_fn(*typ, name);
            
            // Check whether that type has this item as a lookup.
            lookup == Some(fun_id)
        }),
        _ => Box::new(|_: FunId| { true })
    };

    for fun in db.iter_fun() {
        if !filter(fun) { continue; }

        let fun = db.get(fun);
        let Some(name) = fun.name else { continue; };

        let kind = match fun.class {
            Some(_) => CompletionItemKind::METHOD,
            None    => CompletionItemKind::FUNCTION,
        };

        completions.push(CompletionItem {
            label: db.get(name).to_string(),
            label_details: Some(CompletionItemLabelDetails {
                detail: Some(format!(" {}", db.repr_sig(fun.sig).to_string())),
                description: None
            }),
            kind: Some(kind),
            documentation: documentation::inefficient_doc_lsp(db, &fun.doc_comment),
            ..Default::default()
        })
    }
}

fn completions(db: &Db, ast: &Ast, context: &CompletionContext) -> Vec<CompletionItem> {
    let mut completions = Vec::new();

    var_completions(db, context, &mut completions);
    fun_completions(db, context, &mut completions);

    // TODO: Also complete these otherwise...
    if matches!(context, CompletionContext::Unknown) {
        for class in db.iter_class() {
            let class = db.get(class);
            
            completions.push(CompletionItem {
                label: db.get(class.name).to_string(),
                kind: Some(CompletionItemKind::CLASS),
                documentation: documentation::inefficient_doc_lsp(db, &class.doc_comment),
                ..Default::default()
            })
        }
    }

    let mut print = CompletionItem::new_simple("print".to_string(), "Print out any series of expressions.".to_string());
    print.kind = Some(CompletionItemKind::FUNCTION);
    let mut str = CompletionItem::new_simple("str".to_string(), "Convert any series of expressions to a new StrBuf.".to_string());
    str.kind = Some(CompletionItemKind::FUNCTION);

    completions.push(print);
    completions.push(str);

    let do_builtin_types = match context {
        CompletionContext::Unknown => true,
        CompletionContext::MembersOfType(_) => false,
    };

    let do_keywords = match context {
        CompletionContext::Unknown => true,
        CompletionContext::MembersOfType(_) => false,
    };

    let do_annotations = match context {
        CompletionContext::Unknown => true,
        CompletionContext::MembersOfType(_) => false,
    };

    if do_builtin_types {
        builtin_types::builtin_types(&mut completions);
    }

    // Keywords
    if do_keywords {
        keywords::keyword_completions(&mut completions);
    }

    // Annotations
    if do_annotations {
        annotations::annotation_completions(&mut completions);
    }

    completions
}



pub fn completion(store: &mut DocumentStore, params: CompletionParams) -> Option<CompletionResponse> {
    let Some(project) = store.projects.get(&params.text_document_position.text_document.uri) else {
        return None;
    };

    let cached = project.get_cache(store);
    let cached = cached.lock().unwrap();

    let context = if let Some(id) = cached.url_to_id_map.get(&params.text_document_position.text_document.uri) {
        let mut context_finder = CompletionLocator {
            context: CompletionContext::Unknown
        };

        let source_loc = inverse_convert_position(&cached.ast, *id, &params.text_document_position.position);
        context_finder.visit_ast(&cached.ast, &cached.db, &source_loc);

        match context_finder.context {
            CompletionContext::Unknown => eprintln!("completion context: unknown"),
            CompletionContext::MembersOfType(typ) => eprintln!("completion context: members of {}", cached.db.repr_type(typ)),
        }

        context_finder.context
    }
    else {
        CompletionContext::Unknown
    };

    // As a first effort, we will simply provide a list of every symbol in the
    // project. Later, it would be nice to cut down the number of scopes that
    // are used.

    let completions = completions(&cached.db, &cached.ast, &context);

    Some(CompletionResponse::Array(completions))
}