use poniescript_core::{
    db::*,
    expr::*,
    source::*,
};

pub enum Semantic {
    Var(VarId),
    Fun(FunId),
    Class(ClassId),
    Print,
}

// pub struct SemanticRanges<'tok> {
//     origin_selection_range: Option<&'tok SourceLocation>,
//     target_range: &'tok SourceLocation,
//     target_selection_range: &'tok SourceLocation,
// }

struct SemanticLocate<F: FnMut(Semantic, Option<&SourceLocation>)> {
    callback: F,
}

impl<F: FnMut(Semantic, Option<&SourceLocation>)> SemanticLocate<F> {
    fn got_class(&mut self, _ast: &Ast, db: &Db, class: ClassId, origin_selection_range: Option<&SourceLocation>) {
        if class == db.class_unassigned {
            eprintln!("no class :(");
            return;
        }
        (self.callback)(Semantic::Class(class), origin_selection_range);
    }

    fn got_fun(&mut self, _ast: &Ast, _db: &Db, fun: FunId, origin_selection_range: Option<&SourceLocation>) {
        // No unassigned funs...?
        (self.callback)(Semantic::Fun(fun), origin_selection_range);
    }

    fn got_var(&mut self, _ast: &Ast, db: &Db, var: VarId, origin_selection_range: Option<&SourceLocation>) {
        // eprintln!("located var: {}", var.to_index());
        // Don't callback for unassigned var
        if var == db.var_unassigned {
            return;
        }
        (self.callback)(Semantic::Var(var), origin_selection_range);
    }
}

fn cursor_on(cursor: &SourceLocation, target: &SourceLocation) -> bool {
    if cursor.offset < target.offset { return false; }
    if cursor.offset > target.offset + target.length { return false; }
    return true;
}

impl<F: FnMut(Semantic, Option<&SourceLocation>)> LocateAst for SemanticLocate<F> {
    fn locate_assign(&mut self, ast: &Ast, db: &Db, _loc: &SourceLocation, it: &Assign) {
        // TODO: We could just not even do an origin_selection_range here as the
        // default should be correct...?
        self.got_var(ast, db, it.identity,  Some(&it.var_name));
    }

    fn locate_variable(&mut self, ast: &Ast, db: &Db, _loc: &SourceLocation, it: &Variable) {
        self.got_var(ast, db, it.identity, Some(&it.location));
    }

    fn locate_get(&mut self, ast: &Ast, db: &Db, _loc: &SourceLocation, it: &Get) {
        for (val, var) in it.chain.iter().zip(it.vars.iter()) {
            if cursor_on(_loc, &val.location) {
                self.got_var(ast, db, *var, Some(&val.location));
                return;
            }
        }
    }

    fn locate_set(&mut self, ast: &Ast, db: &Db, _loc: &SourceLocation, it: &Set) {
        for (val, var) in it.chain.iter().zip(it.vars.iter()) {
            if cursor_on(_loc, &val.location) {
                self.got_var(ast, db, *var, Some(&val.location));
                return;
            }
        }
    }

    fn locate_new(&mut self, ast: &Ast, db: &Db, loc: &SourceLocation, it: &New) {
        // if cursor_on(loc, &it.identifier.location) {
        //     self.got_class(ast, db, it.class, Some(&it.identifier.location));
        // }
    }

    fn locate_funcall(&mut self, ast: &Ast, db: &Db, loc: &SourceLocation, it: &FunCall) {
        if cursor_on(loc, &it.fn_name) {
            self.got_fun(ast, db, it.identity, Some(&it.fn_name))
        }
    }

    fn locate_funcapture(&mut self, ast: &Ast, db: &Db, loc: &SourceLocation, it: &FunCapture) {
        if cursor_on(loc, &it.fn_name) {
            self.got_fun(ast, db, it.identity, Some(&it.fn_name));
        }
    }

    fn locate_print(&mut self, _ast: &Ast, _db: &Db, _loc: &SourceLocation, it: &Print) {
        // TODO: cursor_on(it.fn_name)
        (self.callback)(Semantic::Print, Some(&it.location));
    }

    fn locate_declare(&mut self, ast: &Ast, db: &Db, loc: &SourceLocation, it: &Declare) {
        if cursor_on(loc, &it.ident) {
            self.got_var(ast, db, it.identity, Some(&it.ident));
        }
    }

    // For now, manually implement the visiting of class declares, because the
    // autogenerated logic doesn't work correctly.
    fn visit_classdeclare(&mut self, ast: &Ast, db: &Db, loc: &SourceLocation, stmt: &ClassDeclare) -> bool {
		let own_loc = &stmt.location;
		eprintln!("visit ClassDeclare: {} ? {} ? {}", own_loc.offset, loc.offset, own_loc.offset + own_loc.length);
		if loc.offset < own_loc.offset { return false; }
		if loc.offset >= own_loc.offset + own_loc.length { return false; }
        for declare in &stmt.vars {
            if self.visit_declare(ast, db, loc, declare) { return true; }
        }
        for fundeclare in &stmt.funs {
            if self.visit_fundeclare(ast, db, loc, fundeclare) { return true; }
        }
		eprintln!("-> found @ ClassDeclare");
		self.locate_classdeclare(ast, db, loc, &stmt);
		return true;
	}

    // For now, also manually implement new, to visit the inner initializers.
    fn visit_new(&mut self, ast: &Ast, db: &Db, loc: &SourceLocation, expr: &New) -> bool {
		let own_loc = &expr.location;
		eprintln!("visit New: {} ? {} ? {}", own_loc.offset, loc.offset, own_loc.offset + own_loc.length);
		if loc.offset < own_loc.offset { return false; }
		if loc.offset >= own_loc.offset + own_loc.length { return false; }
        for init in &expr.initializers {
            if cursor_on(loc, &init.ident.location) {
                self.got_var(ast, db, init.var, Some(&init.ident.location));
                return true;
            }
            if self.visit_expr(ast, db, loc, init.value) {
                return true;
            }
        }
		eprintln!("-> found @ New");
		self.locate_new(ast, db, loc, &expr);
		return true;
	}
}

pub fn semantic_locate<F: FnMut(Semantic, Option<&SourceLocation>)>(ast: &Ast, db: &Db, target: SourceLocation, callback: F) {
    let mut locate = SemanticLocate { callback };
    locate.visit_ast(ast, db, &target);
}
