[package]
name = "ponyquad"
version = "0.1.0"
edition = "2024"

[lib]
# Note: This might have to be cdylib, actually, for wasm. Unclear.
# Also should be 'lib' if we want to link it with other Rust stuff...?
crate-type = ["staticlib", "lib"]

[dependencies]
libloading = "0.9.0"
macroquad = { version = "0.4.14", features = ["backtrace", "log", "log-rs"] }
macroquad-canvas = "0.4.1"
notify = "8.2.0"
poniescript-gc = { version = "0.1.0", path = "../poniescript-gc", features = ["single-threaded"] }
poniescript-rt = { version = "0.1.0", path = "../poniescript-rt" }

[features]
hotreload = ["poniescript-gc/hotreload"]
