use std::fmt::Write;
use std::hash::Hash;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::RwLock;

use crate::error::Error;
// Import relevant things.
use crate::expr::Expr;
use crate::expr::Stmt;
use crate::expr::Fun;
use crate::expr::Sig;
use crate::expr::Class;
use crate::expr::Var;
use crate::typ::Type;
use crate::source::{PathBufFileSource, Source, SourceLocation, SyntheticSource};
use crate::{arena::*, inf_writeln, Args};

use crate::glue::lexer::GlueTok;

use crate::lexer::{Tok, Token};

use rustc_hash::{FxHashMap, FxHashSet};

use crate::arena::IndexCell;

// Include arenas
include!(concat!(env!("OUT_DIR"), "/db.arenas.rs"));

define_arena_key!(ExprId);
define_arena_key!(StmtId);
define_arena_key!(SourceId);

impl ExprId {
	// TODO: Get this back to returning a &SourceLocation, or at least some kind
	// of borrow that points to the SourceLocation.
	//
	// May require jank.
	pub fn location(self, ast: &impl AstAbstract) -> SourceLocation {
		ast.get_expr(self).location().clone()
	}

	pub fn typ(self, ast: &impl AstAbstract, db: &Db) -> TypId {
		ast.get_expr(self).typ(ast, db)
	}

	//pub fn promote(self, typ: TypId, ast: &Ast, db: &Db) -> bool {
	//	ast.exprs.get_mut(self).promote(typ, ast, db)
	//}

	// TODO: Less clones
	pub fn val_location<'a>(self, ast: &'a impl AstAbstract) -> SourceLocation {
		match ast.get_expr(self).as_ref() {
			Expr::Block(block) => {
				if let Some(last) = block.stmts.last() {
					return last.val_location(ast).clone()
				}
				else {
					// If we have no expression at all, the whole block is
					// the closest thing.
					return block.location.clone()
				}
			},

			// Use autogenerated method if we have no special thing.
			_ => return self.location(ast)
		}
	}
}

impl StmtId {
	// TODO: Less clones
	pub fn val_location<'a>(self, ast: &impl AstAbstract) -> SourceLocation {
		ast.get_stmt(self).val_location(ast)
	}

	// pub fn promote(self, typ: TypId, ast: &Ast, db: &Db) -> bool {
	// 	ast.stmts.get_mut(self).promote(typ, ast, db)
	// }
}

pub struct Ast {
	pub exprs: ArenaCell<Expr, ExprId>,
	pub stmts: ArenaCell<Stmt, StmtId>,
	pub sources: ArenaCell<Source, SourceId>,
}

pub struct AstReadonly {
	pub exprs: Arena<Expr, ExprId>,
	pub stmts: Arena<Stmt, StmtId>,
	// For now this doesn't include the Sources because they have a RefCell.
}

pub struct AstReadonlySources {
	pub exprs: Arena<Expr, ExprId>,
	pub stmts: Arena<Stmt, StmtId>,
	pub sources: Arena<Source, SourceId>,
}

pub struct AstProxy<'ar> {
	pub exprs: ArenaCellProxy<'ar, Expr, ExprId>,
	pub stmts: ArenaCellProxy<'ar, Stmt, StmtId>,
	pub sources: ArenaCellProxy<'ar, Source, SourceId>,
}

pub trait AstAbstract {
	fn get_expr_mut(&self, id: ExprId) -> ArenaBorrowMut<'_, Expr, ExprId>;
	fn get_expr(&self, id: ExprId) -> ArenaBorrow<'_, Expr, ExprId>;
	fn get_stmt(&self, id: StmtId) -> ArenaBorrow<'_, Stmt, StmtId>;
}

impl<'ar> AstProxy<'ar> {
	pub fn commit(self) {
		let (exprs, stmts, sources) = (self.exprs, self.stmts, self.sources);
		exprs.commit();
		stmts.commit();
		sources.commit();
	}
}

impl Ast {
	pub fn new() -> Ast {
		Ast {
			exprs: ArenaCell::new(),
			stmts: ArenaCell::new(),
			sources: ArenaCell::new(),
		}
	}

	pub fn into_readonly(self) -> (AstReadonly, Arena<Source, SourceId>) {
		(AstReadonly {
			exprs: self.exprs.into_readonly(),
			stmts: self.stmts.into_readonly(),
		},
			self.sources.into_readonly())
	}

	pub fn from_readonly(ast: AstReadonly, sources: Arena<Source, SourceId>) -> Self {
		Ast {
			exprs: ast.exprs.into_cell(),
			stmts: ast.stmts.into_cell(),
			sources: sources.into_cell(),
		}
	}

	pub fn get_proxy(&mut self) -> AstProxy<'_> {
		return AstProxy {
			exprs: self.exprs.get_proxy(),
			stmts: self.stmts.get_proxy(),
			sources: self.sources.get_proxy()
		}
	}

	pub fn new_source(&mut self, path: PathBuf) -> SourceId {
		self.sources.push(Source::new(PathBufFileSource::new(path)))
	}
}

impl AstAbstract for Ast {
	fn get_expr_mut(&self, id: ExprId) -> ArenaBorrowMut<'_, Expr, ExprId> {
		self.exprs.get_mut(id)
	}

	fn get_expr(&self, id: ExprId) -> ArenaBorrow<'_, Expr, ExprId> {
		self.exprs.get(id)
	}

	fn get_stmt(&self, id: StmtId) -> ArenaBorrow<'_, Stmt, StmtId> {
		self.stmts.get(id)
	}
}

impl<'a> AstAbstract for AstProxy<'a> {
	fn get_expr_mut(&self, id: ExprId) -> ArenaBorrowMut<'_, Expr, ExprId> {
		self.exprs.get_mut(id)
	}

	fn get_expr(&self, id: ExprId) -> ArenaBorrow<'_, Expr, ExprId> {
		self.exprs.get(id)
	}

	fn get_stmt(&self, id: StmtId) -> ArenaBorrow<'_, Stmt, StmtId> {
		self.stmts.get(id)
	}
}

#[derive(Clone, Copy)]
pub enum ScopeEntry {
	Var(VarId),
	Fun(FunId),
	Class(ClassId),

	None
}

pub struct StrProperties {
	length: VarId,
	length_key: StrId,
}

pub struct ArrayProperties {
	length: VarId,
	length_key: StrId,
}

pub struct DbTypes {
	pub str_const: TypId,
	pub str: TypId,
	pub str_buf: TypId,
	pub void: TypId,
	pub unassigned: TypId,
	pub int: TypId,
	pub float: TypId,
	pub bool: TypId,
	pub bottom: TypId,

	pub assume_int: TypId,
	pub assume_float: TypId,

	pub fun_sig_unassigned: TypId,

	// TODO: Consider making these less hard-coded and more "generated" in some
	// way (could allow us to have vec5, vec6, etc..)
	pub vec2: TypId,
	pub vec3: TypId,
	pub vec4: TypId,
	pub vec2i: TypId,
	pub vec3i: TypId,
	pub vec4i: TypId,
}

/// The Db stores all of the arena-allocated objects that can be referenced
/// with Ids. Basically all of these objects live for the entire program.
pub struct Db {
	arenas: DbArenas,

	str_side_map: FxHashMap<String, StrId>,
	type_side_map: FxHashMap<Type, TypId>,
	sig_side_map: FxHashMap<Sig, SigId>,

	sig_cname_cache: FxHashMap<SigId, (&'static str, &'static str)>,
	sig_cdeclared: FxHashMap<SigId, bool>,
	sig_cgenerated: FxHashMap<SigId, bool>,

	array_cname_cache: FxHashMap<TypId, &'static str>,
	array_used: Vec<TypId>,
	//array_cgenerated: FxHashMap<TypId, bool>,

	str_simple_const_map: FxHashMap<String, StrConstId>,

	key_lookup_map: FxHashMap<StrId, Tok>,
	glue_key_lookup_map: FxHashMap<StrId, GlueTok>,

	/// Keep a cache of all generated ctypes so that we can quickly re-use them.
	ctype_cache: Vec<&'static str>,

	known_var_cnames: FxHashMap<VarId, &'static str>,
	known_fun_cnames: FxHashMap<FunId, &'static str>,
	known_class_cnames: FxHashMap<ClassId, &'static str>,

	var_cname_cache: Vec<&'static str>,
	fun_cname_cache: Vec<&'static str>,
	class_cname_cache: Vec<&'static str>,

	/// Keep a cache of generated type reprs also for re-using them.
	/// 
	/// TODO: Supposedly RwLock is needed for LSP stuff. Do we really need it
	/// here?
	type_repr_cache: RwLock<FxHashMap<TypId, &'static str>>,

	fun_cparams_cache: Vec<&'static str>,

	pub fun_init: Option<FunId>,
	pub types: DbTypes,

	pub synthetic: SourceId,
	pub sig_unassigned: SigId,
	pub class_unassigned: ClassId,
	pub var_unassigned: VarId,

	pub errors: Vec<Error>,

	/// Whether we're compiling in a mode where we're testing the compiler.
	/// Useful for comments to support the "expected value" of the test.
	pub test_mode: bool,
	/// The expected lines of output from the program.
	/// Note that these do NOT include the newlines or carriage returns. Those
	/// are assumed to already exist.
	pub test_lines: Vec<String>,
	/// Expected errors from the program.
	/// 
	/// For now, we do not expect any particular error string; if we have any
	/// errors in the test_errors array, we simply expect the compilation to fail.
	pub test_errors: Vec<String>,

	/// Maps names of the form "scope.scope.Item" to ScopeEntries. Used to bind
	/// names to specific objects.
	name_map: FxHashMap<StrId, ScopeEntry>,

	/// Some C code to declare each Sig type.
	pub sig_declare_code: String,

	/// Declares each array struct type.
	pub arr_declare_code: String,
	/// Defines each array struct type.
	pub arr_define_code: String,

	/// Declares each value-typed struct type.
	pub valty_declare_code: String,
	/// Defines each value-typed struct type.
	pub valty_define_code: String,

	/// Defines #define's for each type tag.
	pub tag_define_code: String,
	pub tag_cname_cache: FxHashMap<TypId, &'static str>,

	/// A list of all value types. Needed for sorting them in order.
	/// TODO: This may change a bit when class initializers become a thing.
	///       Those will also essentially be treating things as value types.
	///       It's really mostly a question of which types include which others
	///       as a value.
	pub value_types: Vec<TypId>,

	/// Maps tuple TypIds to their cname.
	pub tuple_cname_cache: FxHashMap<TypId, &'static str>,

	/// Maps StrIds representing '0', '1', etc into indexes into a tuple.
	/// These are generated when a tuple type is created.
	tuple_idxs: FxHashMap<StrId, u32>,

	/// Maps indices with particular types to the associated variables
	/// synthesized for that tuple.
	tuple_vars: FxHashMap<(u32, TypId), VarId>,

	/// TODO: Maybe have only one declare/define code?

	/// Some C code to declare each Array type.
	/// TODO: This doesn't quite work, we really need to do a topological
	/// sort on this stuff.
	// pub arr_declare_code: String,

	pub str_anonymous: StrId,
	pub str_lambda: StrId,
	pub str_lerp: StrId,

	/// The list of globals. The initializer ordering pass will sort them.
	pub globals: Vec<VarId>,

	prop_str: StrProperties,
	prop_array: ArrayProperties,
}

impl Db {
	pub fn new(ast: &mut Ast) -> Self {
		let mut db = unsafe { Db {
			arenas: DbArenas::new(),

			str_side_map: FxHashMap::default(),
			type_side_map: FxHashMap::default(),
			sig_side_map: FxHashMap::default(),

			sig_cname_cache: FxHashMap::default(),
			sig_cdeclared: FxHashMap::default(),
			sig_cgenerated: FxHashMap::default(),

			array_cname_cache: FxHashMap::default(),
			array_used: Vec::new(),

			str_simple_const_map: FxHashMap::default(),

			key_lookup_map: FxHashMap::default(),
			glue_key_lookup_map: FxHashMap::default(),

			ctype_cache: Vec::new(),

			known_var_cnames: FxHashMap::default(),
			known_fun_cnames: FxHashMap::default(),
			known_class_cnames: FxHashMap::default(),

			type_repr_cache: RwLock::new(FxHashMap::default()),
			fun_cparams_cache: Vec::new(),

			var_cname_cache: Vec::new(),
			fun_cname_cache: Vec::new(),
			class_cname_cache: Vec::new(),

			tuple_cname_cache: FxHashMap::default(),

			tuple_vars: FxHashMap::default(),
			tuple_idxs: FxHashMap::default(),

			value_types: Vec::new(),

			errors: Vec::new(),

			fun_init: None,
			types: DbTypes {
				// TODO: Get rid of all these invalid() and instead build these
				// based on the Arena. Might required splitting Db into two
				// pieces.
				str_const: TypId::invalid(),
				str: TypId::invalid(),
				str_buf: TypId::invalid(),
				void: TypId::invalid(),
				unassigned: TypId::invalid(),
				int: TypId::invalid(),
				float: TypId::invalid(),
				bool: TypId::invalid(),
				bottom: TypId::invalid(),

				assume_int: TypId::invalid(),
				assume_float: TypId::invalid(),

				fun_sig_unassigned: TypId::invalid(),

				vec2: TypId::invalid(),
				vec3: TypId::invalid(),
				vec4: TypId::invalid(),
				vec2i: TypId::invalid(),
				vec3i: TypId::invalid(),
				vec4i: TypId::invalid(),
			},

			synthetic: SourceId::invalid(),
			sig_unassigned: SigId::invalid(),
			class_unassigned: ClassId::invalid(),
			var_unassigned: VarId::invalid(),

			name_map: FxHashMap::default(),

			test_mode: false,
			test_lines: Vec::new(),
			test_errors: Vec::new(),

			sig_declare_code: String::new(),

			arr_declare_code: String::new(),
			arr_define_code: String::new(),

			valty_declare_code: String::new(),
			valty_define_code: String::new(),

			tag_define_code: String::new(),
			tag_cname_cache: FxHashMap::default(),

			str_anonymous: StrId::invalid(),
			str_lambda: StrId::invalid(),
			str_lerp: StrId::invalid(),

			prop_str: StrProperties {
				length: VarId::invalid(),
				length_key: StrId::invalid()
			},

			globals: Vec::new(),

			prop_array: ArrayProperties { length: VarId::invalid(), length_key: StrId::invalid() }
		} };

		db.types.str_const  = db.put_type(Type::StrConst);
		db.types.str        = db.put_type(Type::Str);
		db.types.str_buf    = db.put_type(Type::StrBuf);
		db.types.void       = db.put_type(Type::Void);
		db.types.unassigned = db.put_type(Type::Unassigned);
		db.types.int        = db.put_type(Type::Int);
		db.types.float      = db.put_type(Type::Float);
		db.types.bool       = db.put_type(Type::Bool);
		db.types.bottom     = db.put_type(Type::Bottom);

		{
			let f = db.types.float;
			let i = db.types.int;
			db.types.vec2 = db.put_type(Type::Tuple(Arc::from([f, f])));
			db.types.vec3 = db.put_type(Type::Tuple(Arc::from([f, f, f])));
			db.types.vec4 = db.put_type(Type::Tuple(Arc::from([f, f, f, f])));

			db.types.vec2i = db.put_type(Type::Tuple(Arc::from([i, i])));
			db.types.vec3i = db.put_type(Type::Tuple(Arc::from([i, i, i])));
			db.types.vec4i = db.put_type(Type::Tuple(Arc::from([i, i, i, i])));
		}

		db.types.assume_float = db.put_type(Type::AssumeFloat);
		db.types.assume_int = db.put_type(Type::AssumeInt);

		db.synthetic = ast.sources.push(Source::new(SyntheticSource::new()));

		db.sig_unassigned = db.put_sig(&Sig {
			parameters: vec![],
			return_type: db.types.unassigned
		});

		// TODO: Maybe make class_unassigned a special value...?
		// For now it's going to cause some unsafety..

		db.types.fun_sig_unassigned = db.put_type(Type::Fun(db.sig_unassigned));

		db.str_anonymous = db.put_str("<anonymous>");
		db.str_lambda = db.put_str("lambda");
		db.str_lerp = db.put_str("lerp");	

		// Technically, this does waste the initially created
		// HashMap, but the db is created once per whole program run,
		// so it's not a huge inefficiency.
		db.key_lookup_map = crate::lexer::build_key_lookup_map(&mut db);
		db.glue_key_lookup_map = crate::glue::lexer::build_key_lookup_map(&mut db);

		(db.prop_str.length_key, db.prop_str.length) = db.synthesize_property("length", "length", db.types.int);

		(db.prop_array.length_key, db.prop_array.length) = db.synthesize_property("length", "header.length", db.types.int);

		return db;
	}

	pub fn synthetic(&self) -> SourceLocation {
		SourceLocation {
			source: self.synthetic,
			offset: 0,
			length: 0,
		}
	}

	pub fn synthetic_id(&self, name: StrId) -> Token {
		Token {
			typ: Tok::Identifier,
			lexeme: name,
			location: self.synthetic(),
		}
	}

	pub fn synthesize_property(&mut self, str: &str, cname: &'static str, typ: TypId) -> (StrId, VarId) {
		let key = self.put_str(str);
		let var = Var {
			name: key,
			typ,
			fun: None,
			class: None,
			init: false,
			initializer: None,
			location: self.synthetic(),
		};
		let var = self.push(var);

		self.known_var_cnames.insert(var, cname);

		(key, var)
	}

	pub fn know_var_cname(&mut self, var: VarId, cname: &'static str) {
		self.known_var_cnames.insert(var, cname);
	}

	pub fn know_fun_cname(&mut self, fun: FunId, cname: &'static str) {
		self.known_fun_cnames.insert(fun, cname);
	}

	pub fn know_class_cname(&mut self, class: ClassId, struct_cname: &'static str) {
		self.known_class_cnames.insert(class, struct_cname);
	}

	pub fn put_sig(&mut self, sig: &Sig) -> SigId {
		if let Some(existing) = self.sig_side_map.get(sig) {
			return *existing;
		}

		let id = self.push(sig.clone());

		self.sig_side_map.insert(sig.clone(), id);

		id
	}

	// TODO: Return a string, etc..
	pub fn repr_nth_idx(&self, idx: usize) -> usize {
		idx + 1 // 0 -> 1st
	}

	pub fn is_not_concrete(&self, id: TypId) -> bool {
		match self.get(id) {
			Type::AssumeFloat => true,
			Type::AssumeInt => true,

			// TODO: Is unassigned correct here?
			// It seems necessary for empty array literals, but it's not clear.
			Type::Unassigned => true,

			Type::ArrayOf(elem) => self.is_not_concrete(*elem),
			Type::Option(inner) => self.is_not_concrete(*inner),
			Type::Tuple(inner) => {
				for ty in inner.iter() {
					if self.is_not_concrete(*ty) { return true; }
				}
				return false;
			}

			_ => false
		}
	}

	pub fn is_concrete(&self, id: TypId) -> bool {
		return !self.is_not_concrete(id)
	}

	pub fn is_cgen_safe(&self, id: TypId) -> bool {
		match self.get(id) {
			Type::AssumeFloat => false,
			Type::AssumeInt => false,
			Type::Unassigned => false,

			Type::Bottom => false,

			Type::UnboundIdent(_) => false,
			Type::ArrayOf(ty) => self.is_cgen_safe(*ty),
			Type::Tuple(inner) => {
				for ty in inner.iter() {
					if !self.is_cgen_safe(*ty) { return false; }
				}
				true
			}
			Type::Option(inner) => {
				self.is_cgen_safe(*inner)
			}

			_ => true
		}
	}

	pub fn put_str(&mut self, str: &str) -> StrId {
		if let Some(existing) = self.str_side_map.get(str) {
			return *existing;
		}

		let leaked = str.to_owned().leak();

		let id = IdFuncs::<StrId>::push(self, leaked);
		self.str_side_map.insert(leaked.to_string(), id);

		return id;
	}

	/// This function will:
	/// - If the string is already in the side_map, simply clear its buffer
	/// - If the string is NOT in the side map, std::mem::take() it for usage
	///   as the leaked string.
	pub fn put_clear_string(&mut self, str: &mut String) -> StrId {
		if let Some(existing) = self.str_side_map.get(str) {
			str.clear();
			return *existing;
		}

		let str = std::mem::take(str);
		let leaked = str.leak();

		let id = IdFuncs::<StrId>::push(self, leaked);
		self.str_side_map.insert(leaked.to_string(), id);

		return id;
	}

	pub fn put_type(&mut self, typ: Type) -> TypId {
		if let Some(existing) = self.type_side_map.get(&typ) {
			return *existing;
		}

		//let ctype = typ.gen_ctype(self);

		// IMPORTANT: The pushes() here must line up with new_id() -> TypId
		//self.ctype_cache.push(ctype.leak());

		let id = self.push(typ.clone());

		match &typ {
			// For array types, use any type we generate.
			Type::ArrayOf(elem_ty) => self.use_array(*elem_ty),
			Type::Tuple(inner) => self.use_tuple(&inner, id),
			_ => { }
		}

		self.type_side_map.insert(typ, id);

		return id;
	}

	pub fn must_get_type(&self, typ: Type) -> TypId {
		*self.type_side_map.get(&typ).unwrap()
	}

	fn gen_sig_ctype_impl(&mut self, sig_id: SigId) -> (&'static str, &'static str) {
		if let Some(existing) = self.sig_cname_cache.get(&sig_id) {
			return *existing;
		}

		let struct_name = format!("ps_sig_{}", sig_id.0);
		let fnptr_name = format!("ps_sigraw_{}", sig_id.0);

		let result: (&'static str, &'static str) = (fnptr_name.leak(), struct_name.leak());

		self.sig_cname_cache.insert(sig_id, result);
	
		result
	}

	fn gen_type_dependencies(&mut self, typ: TypId) {
		match self.get(typ) {
			Type::FunRaw(sig) | Type::Fun(sig) => {
				self.gen_sig(*sig)
			},

			_ => { }
		}
	}
	
	fn gen_sig(&mut self, sig_id: SigId) {
		use crate::inf_write;
		use crate::inf_writeln;

		if *self.sig_cgenerated.get(&sig_id).unwrap_or(&false) {
			// Return if we've already done it.
			// TODO: This could just be an FxHashSet...
			// Other TODO: Figure out cyclic references (e.g. throw an error
			// if gen_type_dependcies calls use_sig on the same value again)
			return;
		}

		// Now the sig has been generated
		self.sig_cgenerated.insert(sig_id, true);

		let (fnptr_name, struct_name) = self.gen_sig_ctype_impl(sig_id);

		// First, if that sig itself references any other sigs, we have to
		// use_sig() them. This is effectively a topological sort.
		let param_count = self.get(sig_id).parameters.len();
		self.gen_type_dependencies(self.get(sig_id).return_type);
		for i in 0..param_count {
			let param = self.get(sig_id).parameters[i];
			self.gen_type_dependencies(param);
		}

		// Now, we can generate the actual code for that sig.
		let sig = &self.arenas.arena_sig.get(sig_id);

		// TODO: We have to topologically sort these declarations so that ones
		// that use earlier ones work correctly.
		inf_write!(self.sig_declare_code, "typedef {} (*{})(",
			self.get_ctype(sig.return_type),
			fnptr_name);

		// TODO: We should probably just use PONI_ABI() throughout the codebase
		// so we don't have to edit this more in case things change again..?
		inf_write!(self.sig_declare_code, "struct poni_gc_context*");
		for param in &sig.parameters {
			// Always comma thanks to first param
			inf_write!(self.sig_declare_code, ", {}", self.get_ctype(*param));
		}

		// Add closure param
		inf_writeln!(self.sig_declare_code, ", void*);");

		inf_writeln!(self.sig_declare_code, "typedef struct {} {{ {} fun; void* closure; }} {};",
			struct_name, fnptr_name, struct_name);
	}

	pub fn is_sig_used(&self, sig_id: SigId) -> bool {
		self.sig_cdeclared.get(&sig_id).is_some()
	}

	pub fn use_sig(&mut self, sig_id: SigId) {
		if *self.sig_cdeclared.get(&sig_id).unwrap_or(&false) {
			// Return if we've already done it.
			// TODO: This could just be an FxHashSet...
			// Other TODO: Figure out cyclic references (e.g. throw an error
			// if gen_type_dependcies calls use_sig on the same value again)
			return;
		}

		// Now the sig has been used
		self.sig_cdeclared.insert(sig_id, true);
	}

	/// Should only be called by put_type when a type is generated for the first
	/// time. That way, we can track the used arrays in a single Vec without
	/// worrying about pushing redundant copies.
	fn use_array(&mut self, elem_ty: TypId) {
		// We only actually use any array that is cgen safe. This is because
		// we might end up using an intermediate, non-cgen safe type, which is
		// fine, but should never generate into the C code as it will cause
		// a problem.
		if self.is_cgen_safe(elem_ty) {
			self.array_used.push(elem_ty);
		}
	}

	fn use_tuple(&mut self, inner: &Arc<[TypId]>, tuple_ty: TypId) {
		if !self.is_cgen_safe(tuple_ty) { return; }

		self.value_types.push(tuple_ty);

		for (idx, ty) in inner.iter().enumerate() {
			// Generate the StrId for each field index.
			//
			// TODO: OPTIMIZATION: Only do this once for each field index, by keeping
			// track of the max fields converted this way.

			let key = self.put_str(&format!("{idx}"));
			// Use put_str for this so that we don't end up re-leaking the
			// same str over and over.
			let cname = self.put_str(&format!("v_{idx}"));

			// This will end up being re-done many times. Oh well.
			self.tuple_idxs.insert(key, idx as u32);

			let var_key = (idx as u32, *ty);

			// Skip synthesizing the property if it's already been done by
			// another tuple.
			if self.tuple_vars.contains_key(&var_key) { continue; }

			// Now synthesize the property based on our idx, ty pair and
			// add it to the map.
			let (_, var) = self.synthesize_property(self.get(key), self.get(cname), *ty);

			self.tuple_vars.insert(var_key, var);
		}
	}

	/// Generates the ctype for a Sig. Note that this ctype might be nonsense,
	/// but that's OK.
	pub fn gen_sig_ctype(&mut self, sig: SigId) -> &'static str {
		self.gen_sig_ctype_impl(sig).1
	}

	/// Generates the raw ctype for a Sig. Note that this ctype might be nonsense,
	/// but that's OK.
	pub fn gen_sig_raw_ctype(&mut self, sig: SigId) -> &'static str {
		self.gen_sig_ctype_impl(sig).0
	}

	pub fn gen_array_ctype(&mut self, inner_ty: TypId) -> &'static str {
		if let Some(existing) = self.array_cname_cache.get(&inner_ty) {
			return existing;
		}

		let name = format!("struct ps_arr_{}*", inner_ty.0);
		let name = name.leak();
		self.array_cname_cache.insert(inner_ty, name);

		name
	}

	pub fn put_str_const_simple(&mut self, string: &str) -> StrConstId {
		if let Some(existing) = self.str_simple_const_map.get(string) {
			return *existing;
		}

		// Ad-hoc lex of the string literal. This isi for literals of the form
		// "blah blah blah\n\r\t"
		let mut buf = String::new();

		// Skip the quotes on the input token.
		let subrange = &string[1..string.len() - 1].as_bytes();

		buf.push('"');

		let mut idx = 0;
		loop {
			if idx >= subrange.len() { break; }

			match subrange[idx] {
				// For non-ASCII characters, always just represent them in
				// hexadecimal for portability-ish.
				//
				// Also, note that this DOES mean we're allowed to have a literal
				// '\n' inside a string.
				0..31 | 128..=u8::MAX => {
					write!(buf, "\\x{:x}", subrange[idx]).unwrap();
				},
				b'\\' => {
					idx += 1;
					if idx >= subrange.len() {
						todo!("error message for broken string literal {}", string);
					}
					let escaped = subrange[idx];
					match escaped {
						b'n' => buf.push_str("\\n"),
						b'r' => buf.push_str("\\r"),
						b't' => buf.push_str("\\t"),
						b'\\' => buf.push_str("\\\\"),
						b'\"' => buf.push_str("\\\""),
						b'x' => todo!("hexadecimal values in literal {}", string),
						_ => { todo!("error message for broken string literal {}", string); }
					}
				},
				_ => {
					buf.push(subrange[idx] as char);
				}
			}

			idx += 1;
		}

		buf.push('"');

		let id: StrConstId = IdFuncs::<StrConstId>::push(self, buf.clone().leak());
		self.str_simple_const_map.insert(buf, id);
		id
	}

	//pub fn iter_str_const(&self) -> impl Iterator<Item = (StrConstId, &'static str)> + '_ {
	//	self.arenas.arena_strconst.iter().enumerate().map(|(k, v)| (StrConstId(k as u32), *v))
	//}

	pub fn lookup_key(&self, id: StrId) -> Option<Tok> {
		self.key_lookup_map.get(&id).map(|tok| *tok)
	}

	pub fn lookup_glue_key(&self, id: StrId) -> Option<GlueTok> {
		self.glue_key_lookup_map.get(&id).map(|tok| *tok)
	}

	/// Performs an efficient lookup by not generating new StrIds for names
	/// that do not exist.
	pub fn lookup_full_name(&self, name: &str) -> ScopeEntry {
		let Some(id) = self.str_side_map.get(name) else {
			return ScopeEntry::None;
		};

		let Some(entry) = self.name_map.get(id) else {
			return ScopeEntry::None;
		};

		return *entry;
	}

	// TODO: Return the old name for error reporting..?
	pub fn add_full_name(&mut self, name: &str, entry: ScopeEntry) -> Option<ScopeEntry> {
		let name = self.put_str(name);

		self.name_map.insert(name, entry)
	}

	pub fn new_var(&mut self, name: StrId, typ: TypId, fun: Option<FunId>, class: Option<ClassId>, init: bool, initializer: Option<ExprId>, location: SourceLocation) -> VarId {
		let var = Var {
			name,
			typ,
			fun,
			class,
			init,
			initializer,
			location
		};

		return self.push(var);
	}

	pub fn get_cname(&self, var: VarId) -> &'static str {
		// TODO: Cname generation, as well as 'extern C' sort of thing
		unsafe { self.var_cname_cache.get_unchecked(var.to_index()) }
	}

	// These should definitely be cached rather than generated each time, but..
	//
	// TODO: Consider generating the ctypes as soon as we generate a new type
	pub fn get_ctype(&self, typ: TypId) -> &'static str {

		if let Some(existing) = self.ctype_cache.get(typ.to_index()) {
			return *existing;
		}

		// Didn't get the type -- give a helpful panic message.
		let ty_name = self.get(typ).to_string(self);
		panic!("ICE: Tried to get invalid type in get_ctype: {} (TypId {})", ty_name, typ.to_index());

		// Safety: AS LONG AS we don't call new_id outside of put_type,
		// the index must be valid.
		// TODO: Make this code exist in like a "#[cfg(release)] or whatever."
		// unsafe { self.ctype_cache.get_unchecked(typ.to_usize()) }
	}

	pub fn get_var_ctype(&self, var: VarId) -> &'static str {
		self.get_ctype(self.get(var).typ)
	}

	pub fn get_var_type(&self, var: VarId) -> TypId {
		self.get(var).typ
	}

	pub fn get_fun_ret_ctype(&self, fun: FunId) -> &'static str {
		self.get_ctype(self.get(fun).return_type)
	}

	pub fn get_fun_ret_type(&self, fun: FunId) -> TypId {
		self.get(fun).return_type
	}

	/// Should only be called when we know for sure we have the correct
	/// index.
	pub fn get_fun_param_type(&self, fun: FunId, param: usize) -> TypId {
		self.get_var_type(*unsafe { self.get(fun).parameters.get_unchecked(param) })
	}

	pub fn get_sig_param_type(&self, sig: SigId, param: usize) -> TypId {
		*unsafe { self.get(sig).parameters.get_unchecked(param) }
	}

	pub fn get_fun_name(&self, fun: FunId) -> &str {
		if let Some(name) = &self.get(fun).name {
			self.get(*name)
		}
		else {
			"<anonymous>"
		}
	}
	
	pub fn get_fun_cname(&self, fun: FunId) -> &str {
		// TODO: Cname generation
		unsafe { self.fun_cname_cache.get_unchecked(fun.to_index()) }
	}

	pub fn get_fun_return_typid(&self, fun: FunId) -> TypId {
		self.get(fun).return_type
	}

	pub fn does_fun_return_void(&self, fun: FunId) -> bool {
		match self.get(self.get_fun_return_typid(fun)) {
			Type::Void => true, 
			_ => false
		}
	}
	
	pub fn get_fun_cparams(&self, fun: FunId) -> &'static str {
		// This is a bit less safe. It cannot be called until
		// db.generate_fun_cparams_cache() has been called, which can't be
		// called until after type-checking.
		unsafe { self.fun_cparams_cache.get_unchecked(fun.to_index()) }
	}
	
	pub fn get_class_cname(&self, class: ClassId) -> &'static str {
		unsafe { self.class_cname_cache.get_unchecked(class.to_index()) }
	}

	// pub fn get_class_preparer_cname(&self, class: ClassId) -> &'static str {
	// 	unsafe { self.class_preparer_cache.get_unchecked(class.to_index()) }
	// }

	pub fn repr_var(&self, var: VarId) -> &str {
		self.get(self.get(var).name)
	}

	pub fn repr_class(&self, class: ClassId) -> &str {
		self.get(self.get(class).name)
	}

	pub fn repr_var_type(&self, var: VarId) -> &'static str {
		self.repr_type(self.get(var).typ)
	}

	pub fn repr_type(&self, typ: TypId) -> &'static str {
		let mut lock = self.type_repr_cache.write().unwrap();
		if let Some(&cached) = lock.get(&typ) {
			return cached;
		}

		let value = self.get(typ).to_string(self).leak();

		// Note: Using &'static str as the hash map value makes it possible
		// to do this with interior mutability. Maybe we should also do that
		// for ctypes -- although, those the overhead from RefCell is more
		// relevant because we have to generate a LOT of those in the compiled
		// code.
		lock.insert(typ, value);

		value
	}

	pub fn report_error(&mut self, error: Error) {
		self.errors.push(error);
	}

	pub fn type_generates_value(&self, id: TypId) -> bool {
		match self.get(id) {
			Type::Void => false,
			Type::Bottom => false,
			_ => true,
		}
	}

	/// Computes the number of slots that the given type needs if a value of
	/// it is stored.
	/// 
	/// Every value in the type that needs a slot must be stored to the GC
	/// shadow stack at any time that the current thread might be doing a stack
	/// scan.
	pub fn type_gc_slots(&self, id: TypId) -> usize {
		match self.get(id) {
			Type::Int | Type::Float | Type::Bool => 0,
			Type::Void => 0,

			Type::StrConst => 0,
			Type::Str => 1,
			Type::StrBuf => 1,

			Type::FunRaw(_) => 0,
			Type::Fun(_) => 1,

			Type::Bottom => 0,
			Type::Class(_) => 1,
			Type::ArrayOf(_) => 1,
			Type::Tuple(typ_ids) => {
				// TODO: Given that we have to call this function for every
				// single tuple Val that we create, we really should probably
				// cache this values.
				let mut sum = 0;
				for typ in typ_ids.iter() {
					sum += self.type_gc_slots(*typ);
				}
				sum
			},
			Type::Option(id) => {
				// It should require the same number of slots as its inner type
				self.type_gc_slots(*id)
			}
			Type::Unassigned => 0,
			Type::AssumeInt => 0,
			Type::AssumeFloat => 0,
			Type::UnboundIdent(_) => 0,
			Type::UnboundCStructPtr(_) => 0,
		}
	}
	
	pub fn lookup_property(&self, typ: TypId, propname: StrId) -> Option<VarId> {
		let ty = self.get(typ);
		match ty {
			// HACK: Right now these all do the same thing.
			Type::Str | Type::StrConst | Type::StrBuf => {
				if propname == self.prop_str.length_key {
					return Some(self.prop_str.length);
				}

				None
			},
			Type::ArrayOf(_) => {
				if propname == self.prop_array.length_key {
					return Some(self.prop_array.length);
				}

				None
			}
			Type::Class(class_id) => {
				let class = self.get(*class_id);
				let result = class.var_map.get(&propname).copied();
				result
			},
			Type::Tuple(typs) => {
				// Look up the property index based on name ('0' => 0)
				let Some(which_prop) = self.tuple_idxs.get(&propname) else { return None; };

				// We have to manually check the index, this is how we know
				// whether properties are available.
				if (*which_prop as usize) >= typs.len() {
					return None;
				}

				// Now look up the variable based on index-type pair. This should
				// have been generated the first time we used the type.
				self.tuple_vars.get(&(*which_prop, typs[*which_prop as usize])).copied()
			}

			_ => None
		}
	}

	pub fn is_value_type(&self, typ: TypId) -> bool {
		match self.get(typ) {
			Type::Int | Type::Float | Type::Bool | Type::Void => true,
			Type::Tuple(_) => true,
			Type::Option(_) => true,
			_ => false
		}
	}

	// TODO: This is not going to cut it.
	// Things like nested set expressions need to be able to actually hit the
	// value that they are referring to.
	//
	// What we might want to do is treat value types as essentially always being
	// references (e.g. we could create struct ps_tuple *var), and then allocating
	// them separately-ish.
	//
	// Then, we would explicitly add a copy operation whenever a value type
	// is assigned somewhere (i.e. assigned or passed in a function).
	pub fn get_c_member_lookup(&self, typ: TypId) -> &'static str {
		if self.is_value_type(typ) { "." } else { "->" }
	}

	pub fn lookup_member_fn(&self, typ: TypId, propname: StrId) -> Option<FunId> {
		let ty = self.get(typ);
		match ty {
			Type::Class(class_id) => {
				let class = self.get(*class_id);
				class.fun_map.get(&propname).copied()
			}

			_ => None
		}
	}

	fn visit_value_types(&mut self, todo: &mut FxHashSet<TypId>, visited: &mut FxHashSet<TypId>, ordering: &mut Vec<TypId>, typ: TypId) -> Result<(), ()> {
		// Only visit types that still need to be visited.
		if !todo.contains(&typ) {
			return Ok(());
		}

		// If this type was already in the visisted set, that means we have
		// a cycle.
		if !visited.insert(typ) {
			// TODO: Figure out how to get source information
			self.report_error(Error::simple("Cycle in value types".into(), self.synthetic()));
			return Err(());
		}

		// Visit child types.
		match self.get(typ) {
			Type::Tuple(typ_ids) => {
				// TODO: Why. Please. Help
				let typ_ids_clone = typ_ids.clone();

				for inner in typ_ids_clone.iter() {
					self.visit_value_types(todo, visited, ordering, *inner)?;
				}
			},
			// Nothing to visit. Yet.
			_ => {}
		}

		// We are now no longer in the todo set, and we shouldn't be in the
		// visisted set anymore as other types are allowed to see us.
		todo.remove(&typ);
		visited.remove(&typ);

		// Push ourselves to the ordering now, because our children should all
		// be there before us.
		ordering.push(typ);

		Ok(())
	}
	
	pub fn sort_value_types(&mut self) -> Result<(), ()> {
		let mut visited: FxHashSet<TypId> = FxHashSet::default();
		let mut todo: FxHashSet<TypId> = FxHashSet::default();
		let mut ordering: Vec<TypId> = Vec::new();

		for ty in &self.value_types {
			todo.insert(*ty);
		}

		// Take value types so we can iterate over them without the borrow
		// checker complaining.
		let old = std::mem::take(&mut self.value_types);

		for ty in old {
			self.visit_value_types(&mut todo, &mut visited, &mut ordering, ty)?;
		}

		// Now they are in a safe order.
		self.value_types = ordering;

		Ok(())
	}

	fn generate_tags(&mut self) {
		// Start at a somewhat high value so we don't have to update this wrt
		// the standard library too much. We still have to figure out how to
		// import existing tags, of course.
		let mut tag_num = 256u64;
		for typ in self.iter_typ() {
			if !self.is_cgen_safe(typ) { continue; }

			match self.get(typ) {
				Type::Int => { self.tag_cname_cache.insert(typ, "PONI_TAG_INT"); }
				Type::Float => { self.tag_cname_cache.insert(typ, "PONI_TAG_FLOAT"); }
				Type::Bool => { self.tag_cname_cache.insert(typ, "PONI_TAG_BOOL"); }

				Type::Str => { self.tag_cname_cache.insert(typ, "PONI_TAG_STR"); }
				Type::StrBuf => { self.tag_cname_cache.insert(typ, "PONI_TAG_STRBUF"); }
				Type::StrConst => { self.tag_cname_cache.insert(typ, "PONI_TAG_STRCONST"); }
			
				// No tag, as there is no way (?) to store a value of these types.
				Type::Void | Type::Bottom => continue,

				// All arrays use the same tag.
				Type::ArrayOf(_) => { self.tag_cname_cache.insert(typ, "PONI_TAG_ARRAY"); },

				Type::Fun(_) | Type::Class(_) => {
					// This is very sad, but for now we'll just make their name
					// the TypId. We really should make it some kind of relevant
					// string instead.
					let name = format!("PONI_TAG_TY{}", typ.to_nonzero_usize());
					writeln!(self.tag_define_code, "#define {name} 0x{tag_num:x}ULL").unwrap();
					tag_num += 2; // For now, the GC bit is the last bit. This
					// might change.	
					
					self.tag_cname_cache.insert(typ, name.leak());
				}
				Type::FunRaw(_) | Type::Tuple(_) => {
					// This is very sad, but for now we'll just make their name
					// the TypId. We really should make it some kind of relevant
					// string instead.
					let name = format!("PONI_TAG_TY{}", typ.to_nonzero_usize());
					// For now, we'll make value types simply have their high bit
					// set, so we can easily distinguish them.
					writeln!(self.tag_define_code, "#define {name} 0x{:x}ULL", tag_num | 0x8000000000000000).unwrap();
					tag_num += 2; // For now, the GC bit is the last bit. This
					// might change.	
					
					self.tag_cname_cache.insert(typ, name.leak());

				}
				Type::Option(id) => {
					// Because nullable types are the same type, we reuse
					// the tag. (?)
					//
					// For value types, we require a new tag.
					if self.is_value_type(*id) {
						// For now, just do nothing...
						//todo!()
					}
					else {
						let name = format!("PONI_TAG_TY{}", typ.to_nonzero_usize());
						// Generate the macro in terms of the other one (?)
						writeln!(self.tag_define_code, "#define {name} PONI_TAG_TY{}", id.to_nonzero_usize()).unwrap();
						tag_num += 2; // For now, the GC bit is the last bit. This
						// might change.	
						
						self.tag_cname_cache.insert(typ, name.leak());
					}
				}
				Type::Unassigned | Type::AssumeInt | Type::AssumeFloat | Type::UnboundIdent(_) | Type::UnboundCStructPtr(_) => continue,
			}
		}
	}

	pub fn get_type_ctag(&self, typ: TypId) -> &'static str {
		match self.tag_cname_cache.get(&typ) {
			Some(str) => str,
			// For types that don't have a tag, we should not be generating
			// code that involves them. Maybe this should be a panic?
			None => "<compile-err:invalid-tag>",
		}
	}

	pub fn generate_codegen_caches(&mut self, args: &Args) {
		// The order matters, as e.g. var cnames are used for fun cparams.
		self.generate_class_cnames_cache();
		self.generate_ctypes_cache();
		self.generate_var_cnames_cache(args);
		self.generate_fun_cnames_cache();
		self.generate_fun_cparams_cache();
		self.generate_sigs_cache();
		self.generate_arrays_cache();
		self.generate_valtypes_cache();
		self.generate_tags();
	}

	fn generate_valtypes_cache(&mut self) {
		for ty in &self.value_types {
			if !self.is_cgen_safe(*ty) {
				// We should not have pushed any cgen-unsafe types to value_types.
				panic!("ICE: Db.value_types contained non-cgen-safe type");
			}

			// Don't generate anything for these. That said, this seems a bit
			// inefficient or something. It would be nice to improve this.
			// TODO: improve this
			if *ty == self.types.vec2 || *ty == self.types.vec3 || *ty == self.types.vec4
				|| *ty == self.types.vec2i || *ty == self.types.vec3i || *ty == self.types.vec4i
			{
				continue;
			}

			// Go through the arena to avoid borrow checker error.
			match self.arenas.arena_typ.get(*ty) {
				Type::Tuple(members) => {
					// We should have had the cname in the cache.
					let cname = self.tuple_cname_cache.get(ty).unwrap();

					inf_writeln!(self.valty_declare_code, "{};", cname);

					// TODO: We must sort all value types by the way that they are 
					// used. This will also let us detect cycles in value types.
					inf_writeln!(self.valty_define_code, "{} {{", cname);

					let mut idx = 0;

					for member in members.iter() {
						inf_writeln!(self.valty_define_code, "\t{} v_{};",
							self.get_ctype(*member), idx);
						idx += 1;
					}

					inf_writeln!(self.valty_define_code, "}};");
				},
				// No other value types that need to be struct'd yet.
				_ => {}
			}
		}
	}

	fn generate_ctypes_cache(&mut self) {
		for id in self.iter_typ() {
			log::trace!("generate_ctype for {}", self.repr_type(id));

			// It's OK to clone here because types are *somewhat* lightweight
			// (specifically because we're doing all this TypId stuff).
			let ty = self.get(id).clone();

			if let Type::Tuple(_) = &ty {
				// For tuples, first generate the tuple type.
				let ctype = match id {
					id if id == self.types.vec2 => format!("ps_vec2"),
					id if id == self.types.vec3 => format!("ps_vec3"),
					id if id == self.types.vec4 => format!("ps_vec4"),
					id if id == self.types.vec2i => format!("ps_vec2i"),
					id if id == self.types.vec3i => format!("ps_vec3i"),
					id if id == self.types.vec4i => format!("ps_vec4i"),
					_ => format!("struct ps_tuple_{}", id.to_nonzero_usize())
				}.leak();

				// TODO: Maybe Db should just handle all the logic here instead
				// of having the gen_ctype() function on Type?
				self.tuple_cname_cache.insert(id, ctype);
				self.ctype_cache.push(ctype);

				// TODO: Right now we have to skip tuple gen_ctype this way.
				// This really seems ugly.
				continue;
			}

			if let Type::Option(typ) = &ty {
				// Should move this whole thing to Db...?
				if self.is_value_type(*typ) {
					// For value types, we have to generate a wrapper.

					// Right now, these are not ctype safe, but some other
					// todo!() should kill us anyway...?
					self.ctype_cache.push("<unimplemented>");
				}
				else {
					// For reference types, we use a nullable pointer. For function
					// types, it is still a bundle, but the function pointer is null.
					let typ = *typ;
					let ctype = self.get(typ).clone().gen_ctype(self);
					self.ctype_cache.push(ctype.leak());
				}

				continue;
			}

			let ctype = ty.gen_ctype(self);
			self.ctype_cache.push(ctype.leak());
		}
	}

	fn generate_var_cnames_cache(&mut self, args: &Args) {
		let mut used_set = FxHashMap::<StrId, u64>::default();

		for var in self.arenas.arena_var.iter() {
			if let Some(desired) = self.known_var_cnames.get(&var) {
				self.var_cname_cache.push(desired);
				continue;
			}

			let str_id = self.get(var).name;
			let mut cname = match used_set.entry(str_id) {
				std::collections::hash_map::Entry::Occupied(mut val) => {
					let result = *val.get();
					*val.get_mut() += 1;
					format!("v_{}{}", self.get(str_id), result)
				},
				std::collections::hash_map::Entry::Vacant(val) => {
					val.insert(0);
					format!("v_{}", self.get(str_id))
				},
			};

			if args.hot {
				// TODO: Use a hashset?
				if self.globals.contains(&var) {
					// HACK: Just add "*" to the front of the name. That way,
					// whenever it is referenced, it will be a pointer; also,
					// when it is defined, it will be a pointer.
					//
					// Note that we also have to surround it in (). This will
					// have consequences primarily for where it is declared.
					cname = format!("(*{cname})");
				}
			}

			let cname = cname.leak();

			self.var_cname_cache.push(cname);
		}
	}

	fn generate_class_cnames_cache(&mut self) {
		let mut used_set = FxHashMap::<StrId, u64>::default();

		for class in self.arenas.arena_class.iter() {
			if let Some(desired) = self.known_class_cnames.get(&class) {
				self.class_cname_cache.push(desired);
				continue;
			}

			let str_id = self.get(class).name;
			let cname = match used_set.entry(str_id) {
				std::collections::hash_map::Entry::Occupied(mut val) => {
					let result = *val.get();
					*val.get_mut() += 1;
					format!("cl_{}{}", self.get(str_id), result)
				},
				std::collections::hash_map::Entry::Vacant(val) => {
					val.insert(0);
					format!("cl_{}", self.get(str_id))
				},
			};
			let cname = cname.leak();

			self.class_cname_cache.push(cname);
		}
	}

	fn generate_fun_cnames_cache(&mut self) {

		let mut used_set = FxHashMap::<StrId, u64>::default();

		for fun in self.arenas.arena_fun.iter() {
			// TODO: Also put these into the used set? We will probably have to
			// make the known_ dictionaries use StrIds instead of &str
			if let Some(desired) = self.known_fun_cnames.get(&fun) {
				self.fun_cname_cache.push(desired);
				continue;
			}

			// TODO: Actual name mangling and such
			let cname_id = if let Some(name) = &self.get(fun).name {
				*name
			} else { self.str_lambda };

			let cname = match used_set.entry(cname_id) {
				std::collections::hash_map::Entry::Occupied(mut val) => {
					let result = *val.get();
					*val.get_mut() += 1;
					format!("f_{}{}", self.get(cname_id), result)
				},
				std::collections::hash_map::Entry::Vacant(val) => {
					val.insert(0);
					format!("f_{}", self.get(cname_id))
				},
			};

			let cname = cname.leak();
			self.fun_cname_cache.push(cname);
		}
	}

	fn generate_fun_cparams_cache(&mut self) {
		for id in self.arenas.arena_fun.iter() {
			let mut buffer = String::new();

			buffer.push_str("PONI_ABI(");
			
			let mut comma = false;
			for param in &self.get(id).parameters {
				if comma { buffer.push_str(", "); }
				comma = true;

				buffer.push_str(self.get_var_ctype(*param));
				buffer.push(' ');
				buffer.push_str(self.get_cname(*param));
			}

			buffer.push_str(")");

			self.fun_cparams_cache.push(buffer.leak());
		}
	}
	
	fn generate_sigs_cache(&mut self) {
		let sigs = std::mem::take(&mut self.sig_cdeclared);

		for sig in &sigs {
			self.gen_sig(*sig.0);
		}

		// Put sigs back for is_sig_used()
		self.sig_cdeclared = sigs;
	}

	fn gen_array(&mut self, elem_ty: TypId) {
		
		use crate::inf_writeln;

		inf_writeln!(self.arr_declare_code, "struct ps_arr_{};", elem_ty.0);

		inf_writeln!(self.arr_define_code, "struct ps_arr_{} {{", elem_ty.0);
		inf_writeln!(self.arr_define_code, "\tstruct ps_array_header header;");
		inf_writeln!(self.arr_define_code, "\t{} contents[];", self.get_ctype(elem_ty));
		inf_writeln!(self.arr_define_code, "}};");
	}

	fn generate_arrays_cache(&mut self) {
		let arrays = std::mem::take(&mut self.array_used);

		for elem_ty in arrays {
			self.gen_array(elem_ty);
		}
	}
}

/// Lets the Db implement some functions for every type of id.
pub trait IdFuncs<Id> {
	type Object;

	fn get(&self, id: Id) -> &Self::Object;

	fn get_mut(&mut self, id: Id) -> &mut Self::Object;

	fn push(&mut self, t: Self::Object) -> Id;
}