include!(concat!(env!("OUT_DIR"), "/expr.gen.rs"));

use std::mem::MaybeUninit;

use crate::{db::*, lexer::Token};
use crate::source::SourceLocation;
use crate::lexer::Tok;

impl Stmt {
	pub fn val_location(&self) -> &SourceLocation {
		self.location()
	}
}

impl Expr {
	pub fn val_location(&self) -> &SourceLocation {
		match self {
			Expr::Block(block) => {
				if let Some(last) = block.stmts.last() {
					return last.val_location()
				}
				else {
					// If we have no expression at all, the whole block is
					// the closest thing.
					return &block.location
				}
			},

			// Use autogenerated method if we have no special thing.
			_ => return self.location()
		}
	}

	pub fn typ(&self, db: &Db) -> TypId {
		match self {
			Expr::Binary(binary) => {
				binary.typ
			},
			Expr::If(if_) => {
				// Note that ifs are similar to binary expressions.
				if_.typ
			}
			Expr::Variable(var) => {
				db.get_var_type(var.identity)
			},
			Expr::FunCall(call) => {
				db.get_fun_ret_type(call.identity)
			},
			Expr::ValCall(call) => {
				db.get(call.sig).return_type
			},
			Expr::FunCapture(capt) => {
				// db.put_type(Type::Fun(db.get(capt.identity).sig))
				// Maybe store the type on the FunCapture..?
				capt.typ
			},
			Expr::FunDeclare(declare) => {
				// Maybe do it like FunCapture..?
				declare.typ
			}
			Expr::Assign(assign) => {
				db.get_var_type(assign.identity)
			},
			Expr::NumLiteral(lit) => {
				lit.typ
			},
			Expr::StrLiteral(_) => {
				db.types.str_const
			},
			Expr::BoolLiteral(_) => {
				db.types.bool
			},
			Expr::Comparison(_) => {
				db.types.bool
			},
			Expr::Logical(_) => db.types.bool,
			Expr::Block(block) => {
				block.typ
			},
			Expr::Unbound(_) => panic!("calling Expr::typ() on Unbound"),
			Expr::UnboundCall(_) => panic!("calling Expr::typ() on UnboundCall"),
			Expr::Print(print) => {
				print.exprs[0].typ(db)
			},
			Expr::Str(_) => db.types.str_buf,
		}
	}

	pub fn promote(&mut self, typ: TypId, db: &Db) -> bool {
		match self {
			Expr::Binary(binary) => {
				if db.is_not_concrete(binary.typ) && db.is_concrete(typ) {
					// Recursively promote to any concrete type.
					//
					// NOTE that this is still O(n) in the number of AST nodes,
					// because once a type is promoted to concrete once, it cannot
					// have to do it again.
					binary.left.promote(typ, db);
					binary.right.promote(typ, db);
				}
				binary.typ = typ;
				true
			},
			Expr::Comparison(_) => {
				// Types do not propagate down into the comparison. It will
				// promote its own operands, though.
				false
			},
			Expr::Logical(_) => {
				// Does not promote.
				false
			},
			Expr::If(if_) => {
				if db.is_not_concrete(if_.typ) && db.is_concrete(typ) {
					// Same idea as binary.
					if_.then_branch.promote(typ, db);
					if_.else_branch.as_mut().map(|b| b.promote(typ, db));
				}
				if_.typ = typ;
				true
			}
			Expr::Variable(_) => false,
			Expr::Assign(_) => false,
			Expr::FunCall(_) => false,
			Expr::ValCall(_) => false,
			Expr::FunCapture(_) => false,
			Expr::FunDeclare(_) => false,
			Expr::NumLiteral(lit) => {
				lit.typ = typ;
				true
			},
			Expr::StrLiteral(_) => false,
			Expr::BoolLiteral(_) => false,
			Expr::Block(block) => {
				block.typ = typ;
				if let Some(last) = block.stmts.last_mut() {
					return last.promote(typ, db);
				}
				true
			},
			Expr::Unbound(_) => false,
			Expr::UnboundCall(_) => false,
			Expr::Print(print) => {
				print.exprs[0].promote(typ, db)
			},
			Expr::Str(_) => false,
		}
	}
}

impl Stmt {
	pub fn promote(&mut self, typ: TypId, db: &Db) -> bool {
		match self {
			Stmt::Declare(_) => return false,
			Stmt::Expression(expr) => expr.expression.promote(typ, db),

			// The value of a Return is always Bottom, and so it cannot be
			// affected by promote().
			Stmt::Return(_) => return false,
		}
	}
}

/// Information for a variable.
pub struct Var {
	pub name: Token,
	pub typ: TypId,

	pub captured: bool,
}

pub struct Fun {
	pub name: Option<Token>,
	pub sig: SigId,

	/// Parameters are the values when the function is defined, arguments
	/// are the values passed by the caller.
	pub parameters: Vec<VarId>,
	pub return_type: TypId,

	pub captured: bool,
}

/// Represents a function signature. Includes the types of all parameters
/// and of the return value.
#[derive(Clone, PartialEq, Eq, Hash)]
pub struct Sig {
	pub parameters: Vec<TypId>,
	pub return_type: TypId,
}

struct BoxAlloc {
	exprs: &'static mut [MaybeUninit<Expr>],
	stmts: &'static mut [MaybeUninit<Stmt>],

	next_expr: usize,
	next_stmt: usize,
}

static mut alloc: Option<BoxAlloc> = None;

fn get_alloc() -> &'static mut BoxAlloc {
	unsafe {
		if let Some(a) = &mut alloc {
			return a;
		}

		alloc = Some(BoxAlloc {
			exprs: alloc_block(),
			stmts: alloc_block(),

			next_expr: 0,
			next_stmt: 0,
		});

		return get_alloc();
	}
}

fn alloc_block<T>() -> &'static mut [MaybeUninit<T>] {
	unsafe {
		// Copied straight from MaybeUninit::uninit_array
		let a = MaybeUninit::<[MaybeUninit<T>; 512]>::uninit().assume_init();
		return Vec::from(a).leak();
	}
}

pub fn alloc_expr(expr: Expr) -> &'static mut Expr {
	let a = get_alloc();

	if a.next_expr >= a.exprs.len() {
		// TODO: Figure out if there is a way to do this with less syntax...
		a.exprs = alloc_block();
		a.next_expr = 0;
	}

	let idx = a.next_expr;
	a.next_expr += 1;

	let res = &mut a.exprs[idx];
	*res = MaybeUninit::new(expr);

	unsafe { return res.assume_init_mut(); }
}

pub fn alloc_stmt(stmt: Stmt) -> &'static mut Stmt {
	let a = get_alloc();

	if a.next_stmt >= a.stmts.len() {
		// TODO: Figure out if there is a way to do this with less syntax...
		a.stmts = alloc_block();
		a.next_stmt = 0;
	}

	let idx = a.next_stmt;
	a.next_stmt += 1;

	let res = &mut a.stmts[idx];
	*res = MaybeUninit::new(stmt);

	unsafe { return res.assume_init_mut(); }
}
